apiVersion: v1
kind: Secret
metadata:
  name: repo-external-dns
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  url: https://kubernetes-sigs.github.io/external-dns

